# ansible/sistema/tasks/1-base.yml
---
- name: Configurar o TZ para o Brasil
  community.general.timezone:
    name: America/Sao_Paulo

- name: Instalar dependências iniciais
  ansible.builtin.dnf:
    name:
      - glibc-common
      - glibc-locale-source
      - glibc-langpack-pt
    state: present

- name: Configurar LANG no /etc/locale.conf
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=pt_BR.UTF-8'
    create: yes

- name: Instalar Tailspin para facilitar a leitura de logs
  ansible.builtin.unarchive:
    src: https://github.com/bensadeh/tailspin/releases/download/5.4.2/tailspin-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    creates: /usr/local/bin/tspin

- name: Instalar cockpit e firewalld
  ansible.builtin.dnf:
    name:
      - cockpit
      - firewalld
    state: present

- name: Habilitar e iniciar o firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Habilitar e iniciar o cockpit
  ansible.builtin.service:
    name: cockpit
    state: started
    enabled: yes

- name: Definir rede 172.25.0.0/24 como public
  ansible.posix.firewalld:
    zone: public
    source: 172.25.0.0/24
    permanent: yes
    state: enabled
    immediate: yes

- name: Definir rede 172.27.0.0/24 como trusted
  ansible.posix.firewalld:
    zone: trusted
    source: 172.27.0.0/24
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do cockpit esteja aberta na zona public
  ansible.posix.firewalld:
    service: cockpit
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Adicionar IPs de provisionamento no /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].prov_ip }} {{ item }}.osbox.local"
    state: present
    create: yes
  loop: "{{ groups['todos'] }}"

- name: Adicionar IPs de gerenciamento no /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].mgmt_ip }} {{ item }}.mgmt.osbox.local"
    state: present
    create: yes
  loop: "{{ groups['todos'] }}"
