# ansible/sistema/tasks/1-base.yml
---
- name: Configurar o TZ para o Brasil
  community.general.timezone:
    name: America/Sao_Paulo

- name: Instalar dependências iniciais
  ansible.builtin.dnf:
    name:
      - glibc-common
      - glibc-locale-source
      - glibc-langpack-pt
    state: present

- name: Configurar LANG no /etc/locale.conf
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=pt_BR.UTF-8'
    create: yes

- name: Verifica se o binário tspin já está instalado
  ansible.builtin.stat:
    path: /usr/local/bin/tspin
  register: tspin_binary

- name: Baixar e instalar Tailspin com curl se não existir
  ansible.builtin.shell: |
    curl -L https://github.com/bensadeh/tailspin/releases/download/5.4.2/tailspin-x86_64-unknown-linux-musl.tar.gz -o /tmp/tailspin.tar.gz
    tar -xzf /tmp/tailspin.tar.gz -C /usr/local/bin
    chmod +x /usr/local/bin/tspin
    rm -f /tmp/tailspin.tar.gz
  when: not tspin_binary.stat.exists
  args:
    creates: /usr/local/bin/tspin

