# ansible/sistema/tasks/1-base.yml
---
- name: Configurar o TZ para o Brasil
  community.general.timezone:
    name: America/Sao_Paulo

- name: Instalar dependências iniciais
  ansible.builtin.dnf:
    name:
      - glibc-common
      - glibc-locale-source
      - glibc-langpack-pt
    state: present

- name: Configurar LANG no /etc/locale.conf
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=pt_BR.UTF-8'
    create: yes
