# ansible/sistema/tasks/2-services.yml
---
- name: Instalar Tailspin para facilitar a leitura de logs
  ansible.builtin.unarchive:
    src: https://github.com/bensadeh/tailspin/releases/download/5.4.2/tailspin-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    creates: /usr/local/bin/tspin

- name: Instalar cockpit, firewalld e dependências
  ansible.builtin.dnf:
    name:
      - cockpit
      - firewalld
      - pcp
      - python3-pcp
      - cockpit-session-recording
      - cockpit-files
      - cockpit-storaged
    state: present

- name: Habilitar e iniciar os serviços instalados
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - cockpit
    - firewalld
    - pmlogger

- name: Associar eth0 à zona dmz (rede do vagrant)
  ansible.posix.firewalld:
    interface: eth0
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do ssh esteja aberta na zona dmz
  ansible.posix.firewalld:
    service: ssh
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes

- name: Associar eth1 à zona trusted (tráfego entre VMs)
  ansible.posix.firewalld:
    interface: eth1
    zone: trusted
    permanent: yes
    state: enabled
    immediate: yes

- name: Associar eth2 à zona public (acesso ao cluster)
  ansible.posix.firewalld:
    interface: eth2
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do cockpit esteja aberta na zona public
  ansible.posix.firewalld:
    service: cockpit
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do ssh esteja aberta também na zona public
  ansible.posix.firewalld:
    service: ssh
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Construir conteúdo do /etc/hosts com todos os nós
  ansible.builtin.set_fact:
    osbox_hosts_block: |
      127.0.0.1 localhost localhost.localdomain
      ::1       localhost localhost.localdomain
      {% for item in groups['todos'] %}
      {{ hostvars[item].mgmt_ip }} {{ item }} {{ item }}.osbox.local
      {% endfor %}

- name: Substituir todo o /etc/hosts com conteúdo gerenciado
  ansible.builtin.copy:
    dest: /etc/hosts
    content: "{{ osbox_hosts_block | trim }}\n"
    owner: root
    group: root
    mode: '0644'
    backup: yes
