# ansible/sistema/tasks/2-services.yml
---
- name: Instalar Tailspin para facilitar a leitura de logs
  ansible.builtin.unarchive:
    src: https://github.com/bensadeh/tailspin/releases/download/5.4.2/tailspin-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    creates: /usr/local/bin/tspin

- name: Instalar cockpit, firewalld e dependências
  ansible.builtin.dnf:
    name:
      - cockpit
      - firewalld
      - pcp
      - python3-pcp
      - cockpit-session-recording
      - cockpit-files
      - cockpit-storaged
    state: present

- name: Habilitar e iniciar os serviços instalados
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - cockpit
    - firewalld
    - pmlogger

- name: Criar a zona vagrant
  ansible.posix.firewalld:
    zone: vagrant
    state: present
    permanent: yes

- name: Associar eth0 à zona dmz
  ansible.posix.firewalld:
    interface: eth0
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do ssh esteja aberta na zona dmz
  ansible.posix.firewalld:
    service: ssh
    zone: dmz
    permanent: yes
    state: enabled
    immediate: yes

- name: Associar eth1 à zona trusted (tráfego entre VMs)
  ansible.posix.firewalld:
    interface: eth1
    zone: trusted
    permanent: yes
    state: enabled
    immediate: yes

- name: Associar eth2 à zona public (acesso ao cluster)
  ansible.posix.firewalld:
    interface: eth2
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do cockpit esteja aberta na zona public
  ansible.posix.firewalld:
    service: cockpit
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Garantir que a porta do ssh esteja aberta também na zona public
  ansible.posix.firewalld:
    service: ssh
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Adicionar IPs de gerenciamento no /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].mgmt_ip }} {{ item }} {{ item }}.osbox.local"
    state: present
    create: yes
  loop: "{{ groups['todos'] }}"
