# ansible/sistema/tasks/main.yml
---
- name: Instalação do Sistema Base
  ansible.builtin.import_tasks: '1-base.yml'
  tags:
    - sistema

- name: Instalação de Serviços Comuns
  ansible.builtin.import_tasks: '2-services.yml'
  tags:
    - sistema