# -*- mode: ruby -*-
# vi: set ft=ruby :

# Para executar no LibVirt sem precisar de senha de root:
# - sudo usermod -a -G libvirt $(whoami)
# - sudo usermod -a -G kvm $(whoami)
# - sudo usermod -a -G libvirt-qemu $(whoami)

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"
PROJETO = "osbox"

# Definição dos nodes com seus IPs e recursos
nodes = {
  "controller01" => { "prov_ip" => "172.25.0.11", 
                      "mgmt_ip" => "172.27.0.11", 
                      "memory" => 4096, "cpus" => 2 },
  "compute01"    => { "prov_ip" => "172.25.0.21", 
                      "mgmt_ip" => "172.27.0.21", 
                      "memory" => 4096, "cpus" => 2 },
  "compute02"    => { "prov_ip" => "172.25.0.22", 
                      "mgmt_ip" => "172.27.0.21", 
                      "memory" => 2048, "cpus" => 1 },
  "blkstorage01" => { "prov_ip" => "172.25.0.31", 
                      "mgmt_ip" => "172.27.0.31", 
                      "memory" => 2048, "cpus" => 1 },
  "objstorage01" => { "prov_ip" => "172.25.0.32", 
                      "mgmt_ip" => "172.27.0.12", 
                      "memory" => 2048, "cpus" => 1 }
}

Vagrant.configure("2") do |config|
  # Gera a chave SSH se não existir
  unless File.exist?('id_ed25519') && File.exist?('id_ed25519.pub')
    system('ssh-keygen -t ed25519 -f id_ed25519 -N "" >/dev/null 2>&1')
    puts "Nova chave SSH gerada."
  end

  # Remove as chaves após destruir todas as VMs
  config.trigger.after :destroy do |trigger|
    trigger.ruby do |env, machine|
      if File.exist?('id_ed25519')
        File.delete('id_ed25519')
        File.delete('id_ed25519.pub')
        puts "Chave SSH removida."
      end
    end
  end

  # Imagem a ser utilizada
  config.vm.box = "almalinux/9"
  config.vm.post_up_message = ""
  config.ssh.insert_key = false
  config.vm.synced_folder "./", "/vagrant", type: "virtiofs"

  # Configuração comum para todas as VMs (LibVirt)
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memorybacking :source, :type => "memfd"
    libvirt.memorybacking :access, :mode => "shared"

    libvirt.cpu_mode = "host-model"
    libvirt.nested = true

    libvirt.nic_model_type = "virtio"
    libvirt.management_network_name = "vagrant"
    libvirt.management_network_address = "192.168.250.0/24"
    libvirt.management_network_mode = "none"
    libvirt.management_network_autostart = true
  end

  nodes.each do |node_name, specs|
    config.vm.define node_name, autostart: ENV['MON'] ? true : specs.fetch("as", true) do |node|
      node.vm.hostname = node_name
      
      # Configurações de rede para o projeto
      node.vm.network "private_network", ip: specs["prov_ip"],
          libvirt__network_name: "#{PROJETO}_prov",
          libvirt__dhcp_enabled: false

      node.vm.network "private_network", ip: specs["mgmt_ip"],
          libvirt__network_name: "#{PROJETO}_mgmt",
          libvirt__forward_mode: "veryisolated",
          libvirt__network_address: "172.27.0.0/24",
          libvirt__dhcp_enabled: false

      # Sobrescreve as configurações de memória e CPU para cada VM
      node.vm.provider :libvirt do |libvirt_host|
        libvirt_host.default_prefix = "#{PROJETO}_"
        libvirt_host.memory = specs["memory"]
        libvirt_host.cpus = specs["cpus"]
      end

      # Adiciona a chave pública se ela não existir
      node.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          PUBKEY=$(cat /vagrant/id_ed25519.pub)
          if ! grep -q "$PUBKEY" /home/vagrant/.ssh/authorized_keys; then
            echo "$PUBKEY" >> /home/vagrant/.ssh/authorized_keys
            echo "Chave SSH adicionada."
          else
            echo "A chave SSH já existe no arquivo authorized_keys."
          fi
        SHELL
      end

      # Ajuste da rota padrão das máquinas usando os IPs do VagrantFile
      node.vm.provision "shell" do |net|
        net.inline = <<-SHELL
          nmcli con mod "eth0" connection.id net_vagrant
          nmcli con mod "System eth1" connection.id net_prov
          nmcli con mod "System eth2" connection.id net_mgmt

          nmcli con mod net_prov ipv4.never-default no
          nmcli con mod net_prov ipv4.gateway 172.25.0.1 ipv4.route-metric 50
          nmcli con mod net_prov ipv4.dns "1.1.1.1 8.8.8.8"

          nmcli con down net_prov && nmcli con up net_prov
        SHELL
      end
    end
  end
end
