# ansible/playbook.yml
---
- name: Configurações base para todas as máquinas
  hosts: todos
  become: true
  gather_facts: true
  roles:
    - role: sistema
      tags:
        - sistema
        - todas

- name: Configurações específicas dos controllers
  hosts: controllers
  become: true
  gather_facts: true
  roles:
    - role: controller
      tags:
        - controller
        - todas